/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;
import java.util.ArrayList;
import source.*;

/**
 *
 * @author User
 */
public class SuggestionWindow extends javax.swing.JFrame {

    /**
     * Creates new form SuggestionWindow
     */
    
    static int numberOfQuestions = 6;
     ArrayList<String> questions = new ArrayList();
     ArrayList<String> jRadioButton1Text = new ArrayList();
     ArrayList<String> jRadioButton2Text = new ArrayList();
     ArrayList<String> jRadioButton3Text = new ArrayList();
     ArrayList<String> jRadioButton4Text = new ArrayList();
     
     int count = 1;
     int score = 0;

    
    public SuggestionWindow() {
        initComponents();
        setLocationRelativeTo( null ); //to center the window
        jRadioButton3.setVisible(false);
        jRadioButton4.setVisible(false);
        
 
        // questions
        questions.add("What is your sex?"); // first question
        questions.add("What is your age?");
        questions.add("What is your education?");
        questions.add("What is your occupation?");
        questions.add("How many hours do you use computer in a day?");
        questions.add("What is your income (monthly in TL)?");
        
        // jRadioButton1Text
        jRadioButton1Text.add("Male");
        jRadioButton1Text.add("<18");
        jRadioButton1Text.add("Primary School");
        jRadioButton1Text.add("Student");
        jRadioButton1Text.add("<2");
        jRadioButton1Text.add("<1000");
        
        // jRadioButton2Text
        jRadioButton2Text.add("Female");
        jRadioButton2Text.add("18-26");
        jRadioButton2Text.add("High School");
        jRadioButton2Text.add("Officer");
        jRadioButton2Text.add("2-4");
        jRadioButton2Text.add("1000-2500");
        
        // jRadioButton3Text
        jRadioButton3Text.add("NULL");
        jRadioButton3Text.add("26-35");
        jRadioButton3Text.add("Collage");
        jRadioButton3Text.add("Engineer");
        jRadioButton3Text.add("4-6");
        jRadioButton3Text.add("2500-5000");
        
        // jRadioButton4Text
        jRadioButton4Text.add("NULL");
        jRadioButton4Text.add(">35");
        jRadioButton4Text.add("Graduate School");
        jRadioButton4Text.add("Unemployed");
        jRadioButton4Text.add(">6");
        jRadioButton4Text.add(">5000");
        
        
            
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Suggestion Questions", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 1, 12))); // NOI18N

        jLabel1.setText("What is your sex?");

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Male");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Female");

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("jRadioButton3");

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setText("jRadioButton4");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jRadioButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton4))
                    .addComponent(jLabel1))
                .addContainerGap(153, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jRadioButton1, jRadioButton2, jRadioButton3, jRadioButton4});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton3)
                    .addComponent(jRadioButton4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setText("Exit");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setText("Next");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton1, jButton2});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
      
      if (count == numberOfQuestions)
      {
          // finished
          // to do
          if (score > 0 && score <= 100 )    {
              // to do
              
              new SuggestionResultWindow();
              
              this.dispose();
          }
          else if (score > 100 && score <= 200 )    {
              // to do
              this.dispose();
          }
          else if (score > 200 && score <= 300 )    {
              // to do
              this.dispose();
          }
          else {
              // to do
              this.dispose();
          }
          
      }
      else
      {  
          jLabel1.setText(questions.get(count));
          
          jRadioButton1.setText(jRadioButton1Text.get(count));
          jRadioButton2.setText(jRadioButton2Text.get(count));
          
          // radioButton3 and radioButton4 can be NULL
          if (jRadioButton3Text.get(count).equals("NULL") ) 
              jRadioButton3.setVisible(false);
          else  {
              jRadioButton3.setVisible(true);
              jRadioButton3.setText(jRadioButton3Text.get(count));
          }
              
          
          if (jRadioButton4Text.get(count).equals("NULL") ) 
              jRadioButton4.setVisible(false);
          else  {
              jRadioButton4.setText(jRadioButton4Text.get(count));
              jRadioButton4.setVisible(true);
              
          }
          
          // puan tutma
          if (count == 1)    {
              
              if(jRadioButton1.isSelected()){
                  score += 50;
                }
              else{
                  score += 25;
              }
              
          }
          else if (count == 2) {
              
              if(jRadioButton1.isSelected()){
                  score += 40;
                }
              else if (jRadioButton2.isSelected())  {
                  score += 60;
              }
              else if (jRadioButton3.isSelected())  {
                  score += 40;
              }
              else  {
                  score += 20;
              }
              
          }
          
           else if (count == 3) {
              
              if(jRadioButton1.isSelected()){
                  score += 10;
                }
              else if (jRadioButton2.isSelected())  {
                  score += 20;
              }
              else if (jRadioButton3.isSelected())  {
                  score += 40;
              }
              else  {
                  score += 70;
              }
              
          }
          
          else if (count == 4) {
              
              if(jRadioButton1.isSelected()){
                  score += 80;
                }
              else if (jRadioButton2.isSelected())  {
                  score += 30;
              }
              else if (jRadioButton3.isSelected())  {
                  score += 60;
              }
              else  {
                  score += 10;
              }
              
          }
          
          else if (count == 5) {
              
              if(jRadioButton1.isSelected()){
                  score += 10;
                }
              else if (jRadioButton2.isSelected())  {
                  score += 40;
              }
              else if (jRadioButton3.isSelected())  {
                  score += 80;
              }
              else  {
                  score += 120;
              }
              
          }
          
          else {
              
              if(jRadioButton1.isSelected()){
                  score += 20;
                }
              else if (jRadioButton2.isSelected())  {
                  score += 40;
              }
              else if (jRadioButton3.isSelected())  {
                  score += 80;
              }
              else  {
                  score += 120;
              }
              
          }
            
              
          
          
          count++;
      }
         
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        new UserHelpMenu(null).setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SuggestionWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SuggestionWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SuggestionWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SuggestionWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new SuggestionWindow().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    // End of variables declaration//GEN-END:variables
}
